services:
  6sense-team-pulse-backend:
    image: ghcr.io/6sense-technologies/6sense-team-pulse-backend:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:3000"
    environment:
      - NODE_ENV=production
      - IMAGE_TAG=${IMAGE_TAG}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - HOST_PORT=${HOST_PORT}
      - MONGODB_URL=${MONGODB_URL}
      - TRELLO_API_KEY=${TRELLO_API_KEY}
      - TRELLO_SECRET_KEY=${TRELLO_SECRET_KEY}
      - LINEAR_CLIENT_ID=${LINEAR_CLIENT_ID}
      - LINEAR_CLIENT_SECRET=${LINEAR_CLIENT_SECRET}
      - LINEAR_REDIRECT_URI=${LINEAR_REDIRECT_URI}
      - REDIS_URL=${REDIS_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - GITHUB_API_URL=${GITHUB_API_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - OTP_PRIVATE_KEY=${OTP_PRIVATE_KEY}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_SERVICE_PORT=${EMAIL_SERVICE_PORT}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - JWT_EXPIRE_REFRESH_TOKEN=${JWT_EXPIRE_REFRESH_TOKEN}
      - SALT_ROUND=${SALT_ROUND}
      - INVITE_SECRET=${INVITE_SECRET}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - FRONTEND_URL=${FRONTEND_URL}
      - INVITE_EXPIRE=${INVITE_EXPIRE}
      - IMGBB_API_KEY=${IMGBB_API_KEY}
    networks:
      - 6sensehq_net

networks:
  6sensehq_net:
    external: true
    name: 6sensehq-network