version: "3.8"
services:
  nestjs-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_OPTIONS=--max-old-space-size=512
    deploy:
      resources:
        limits:
          memory: 512M